# theme: jekyll-theme-myst729

title: dg
typeof: Object.prototype.toString.call(dg)
tagline: '"[object WebDev]"'
baseurl: /
herolink: posts
excerpt_separator: <!-- more -->

avatar:
  png: /assets/avatar.png
  svg: /assets/avatar.svg
  anima: /assets/avatar-animation.svg
  favicon: /assets/avatar-favicon.png

issues:
  - link: myself
    icon: flower
    descripton: "Myself"
  - link: french
    icon: france
    descripton: "Fran√ßais"

social:
  - id: github
    url: https://github.com/myst729
    descripton: "GitHub"
  - id: stackoverflow
    url: https://stackoverflow.com/users/1032492
    descripton: "Stack Overflow"
  - id: twitter
    url: https://twitter.com/myst729
    descripton: "Twitter"
    inactive: true
  - id: weibo
    url: https://weibo.com/myst729
    descripton: "Weibo"
    inactive: true

themes: standard # lite, standard

sass:
  style: :compressed

plugins:
  - jekyll-minifier

jekyll-minifier:
  uglifier_args:
    harmony: true
